server:
  port: 12000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/fan_hailong/heaven_springCloud_config_demo.git
    rabbitmq:
      host: localhost
      port: 5627
      username: guest
      password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10087/eureka
    instance:
      ip-address: 127.0.0.1
      prefer-ip-address: true
logging:
  level:
    com: debug
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
